Syntax 2

SectionUseCase."HiFi" {
	File "HiFi.conf"
	Comment "Play HiFi quality music"
}


BootSequence [
	# Playback volumes.
	cset "name='DAC Volume' 63"
	cset "name='LINEOUT Gain' 10"
	cset "name='HPOUT Gain' 7"

	# Capture volumes.
	cset "name='ADC1 Gain' 31"
	cset "name='ADC2 Gain' 31"
	cset "name='ADC3 Gain' 0"

	# Setup muxes / switches
	cset "name='LINEOUTL Switch' on"
	cset "name='LINEOUTR Switch' on"
	cset "name='SPK Switch' on"
	cset "name='HPOUT Switch' on"
	cset "name='Headphone Switch' on"
	cset "name='MIC1 Switch' on"
	cset "name='MIC2 Switch' on"
]

SectionDefaults [
	# Switch playback off.
	cset "name='LINEOUTL Switch' off"
	cset "name='LINEOUTR Switch' off"
	cset "name='SPK Switch' off"
	cset "name='HPOUT Switch' off"
	cset "name='Headphone Switch' off"

	# Switch capture off.
	cset "name='MIC1 Switch' off"
	cset "name='MIC2 Switch' off"
	cset "name='MIC3 Switch' off"
]
